# Generated by Django 5.1 on 2024-09-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('price_list_type', models.CharField(max_length=50)),
                ('percentage_type', models.CharField(max_length=50)),
                ('round_off_to', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
