# Generated by Django 5.0 on 2024-09-21 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_pricelist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('returnableItem', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssociatedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_services', to='api.compositeitem')),
            ],
        ),
        migrations.CreateModel(
            name='AssociatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_items', to='api.compositeitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('returnable_item', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
