# Generated by Django 5.0 on 2024-09-21 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_pricelist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='user_id',
            new_name='user',
        ),
    ]
