# Generated by Django 5.1 on 2024-09-24 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_itemgroup_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255)),
                ('bill_number', models.CharField(max_length=50)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_terms', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
